//
//  SendDataPresenter.swift
//  Data-Passing-CleanSwift
//
//  Created by Krish on 19/06/19.
//  Copyright (c) 2019 Krish. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SendDataPresentationLogic
{
  func presentSomething(response: SendData.Something.Response)
}

class SendDataPresenter: SendDataPresentationLogic
{
  weak var viewController: SendDataDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: SendData.Something.Response)
  {
    let viewModel = SendData.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
