//
//  SendDataInteractor.swift
//  Data-Passing-CleanSwift
//
//  Created by Krish on 19/06/19.
//  Copyright (c) 2019 Krish. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SendDataBusinessLogic
{
  func doSomething(request: SendData.Something.Request)
}

protocol SendDataDataStore
{
  //var name: String { get set }
}

class SendDataInteractor: SendDataBusinessLogic, SendDataDataStore
{
  var presenter: SendDataPresentationLogic?
  var worker: SendDataWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: SendData.Something.Request)
  {
    worker = SendDataWorker()
    worker?.doSomeWork()
    
    let response = SendData.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
