//
//  GetDataInteractor.swift
//  Data-Passing-CleanSwift
//
//  Created by Krish on 19/06/19.
//  Copyright (c) 2019 Krish. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol GetDataBusinessLogic
{
  func doSomething(request: GetData.Something.Request )
}

protocol GetDataDataStore
{
  //var name: String { get set }
}

class GetDataInteractor: GetDataBusinessLogic, GetDataDataStore
{
  var presenter: GetDataPresentationLogic?
  var worker: GetDataWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: GetData.Something.Request)
  {
    worker = GetDataWorker()
    worker?.doSomeWork()
    
    let response = GetData.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
