//
//  GetDataRouter.swift
//  Data-Passing-CleanSwift
//
//  Created by Krish on 19/06/19.
//  Copyright (c) 2019 Krish. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol GetDataRoutingLogic
{
  func routeToSomewhere(segue: UIStoryboardSegue?)
}

protocol GetDataDataPassing
{
  var dataStore: GetDataDataStore? { get }
}

class GetDataRouter: NSObject, GetDataRoutingLogic, GetDataDataPassing
{
  weak var viewController: GetDataViewController?
  var dataStore: GetDataDataStore?
  
 //  MARK: Routing
  
  func routeToSomewhere(segue: UIStoryboardSegue?)
  {
    let storyboard = UIStoryboard(name: "Main", bundle: nil)
    let destinationVC = storyboard.instantiateViewController(withIdentifier: "SendDataViewController") as! SendDataViewController
   // let destinationDS = destinationVC.router!.dataStore!
    //  passDataToSomewhere(source: dataStore!, destination: &destinationDS)
      navigateToSomewhere(source: viewController!, destination: destinationVC)
    }
  

  // MARK: Navigation
  
  func navigateToSomewhere(source: GetDataViewController, destination: SendDataViewController)
  {
    source.show(destination, sender: nil)
  }
  
  // MARK: Passing data
  
//  func passDataToSomewhere(source: GetDataDataStore, destination: inout SomewhereDataStore)
//  {
//    destination.name = source.name
//  }
  }


