//
//  GetDataPresenter.swift
//  Data-Passing-CleanSwift
//
//  Created by Krish on 19/06/19.
//  Copyright (c) 2019 Krish. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol GetDataPresentationLogic
{
  func presentSomething(response: GetData.Something.Response)
}

class GetDataPresenter: GetDataPresentationLogic
{
  weak var viewController: GetDataDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: GetData.Something.Response)
  {
    let viewModel = GetData.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
