//
//  GetDataModels.swift
//  Data-Passing-CleanSwift
//
//  Created by Krish on 19/06/19.
//  Copyright (c) 2019 Krish. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum GetData
{
  // MARK: Use cases
  
  enum Something
  {
    struct Request
    {
    }
    struct Response
    {
    }
    struct ViewModel
    {
    }
  }
}


struct WelcomeElement: Codable {
//    let userID, id: Int
    let title: String
//    let completed: Bool
    
    enum CodingKeys: String, CodingKey {
//        case userID = "userId"
//        case id, title, completed
          case title
    }
}

typealias Welcome = [WelcomeElement]
