//
//  GetDataWorker.swift
//  Data-Passing-CleanSwift
//
//  Created by Krish on 19/06/19.
//  Copyright (c) 2019 Krish. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class GetDataWorker
{
    var someData:WelcomeElement?
    var urlRequest:URLRequest!
    
  func doSomeWork()
  {
     urlRequest = URLRequest(url: URL(string: "https://jsonplaceholder.typicode.com/todos/21")!)
     urlRequest.httpMethod = "GET"
     URLSession.shared.dataTask(with: urlRequest) { (data, responce, error) in
     print(data as Any)
        
        do{
           self.someData = try JSONDecoder().decode(WelcomeElement.self, from: data!)
           DispatchQueue.main.async {
            if self.someData != nil{
               print(self.someData! as Any )
            }
            
            }
        }catch{
                print("unable to Respond")
            }
        }.resume()
        
    }
  }

